chendian/api/member/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf.urls import patterns, url

from .views import (
    MemberList, MemberDetail, NewMemberApprove, CheckinList, BookList
)

urlpatterns = patterns(
    '',
    url(r'^$', MemberList.as_view(),
        name='member_list'),
    url(r'^(?P<pk>\d+)/$', MemberDetail.as_view(),
        name='member_detail'),
    url(r'^new_member/(?P<pk>\d+)/approve/$', NewMemberApprove.as_view(),
        name='new_member_approve'),

    url(r'^(?P<pk>\d+)/checkins/$', CheckinList.as_view(),
        name='checkin_list'),

    url(r'^(?P<pk>\d+)/books/$', BookList.as_view(),
        name='book_list'),
)

chendian/chendian/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import permission_required
# from django.views.generic import TemplateView

from qq.views.index import HomeListView

login_url = 'login'
admin_prefix = settings.ADMIN_PREFIX

urlpatterns = patterns(
    '',

    # Examples:
    # url(r'^$', 'chendian.views.home', name='home'),
    url(r'^admin123/$', permission_required(
        'member.member_add', login_url=login_url
    )(HomeListView.as_view()), name='admin123'
    ),
    url(r'^admin123/', include('qq.urls', namespace='qq')),
    url(r'^admin123/members/', include('member.urls', namespace='member')),
    url(r'^admin123/books/', include('book.urls', namespace='book')),
    url(r'^admin123/blog/', include('blog.urls', namespace='blog')),
    url(r'^api/', include('api.urls', namespace='api')),
    # url(r'^blog/', include('blog.urls')),

    url(r'^%s/' % admin_prefix, include(admin.site.urls)),

    url(r'', include('frontend.urls', namespace='frontend')),
)

urlpatterns += patterns(
    '',
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^login/$', 'member.views.login', name='login'),
    url(r'^logout/$', 'member.views.logout', name='logout'),
    url(r'^change-password/$', 'member.views.change_password',
        name='change_password'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

chendian/member/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals
import functools

from django.conf.urls import patterns, url
from django.contrib.admin.views.decorators import staff_member_required

from .views import MemberListView, NewMemberListView

login_url = 'login'
staff_member_required = functools.partial(
    staff_member_required, login_url=login_url
)

urlpatterns = patterns(
    '',
    url(
        r'^$', staff_member_required(MemberListView.as_view()),
        name='member_list'
    ),
    url(
        r'^new/$',
        staff_member_required(NewMemberListView.as_view()),
        name='new_member_list'
    ),
)

chendian/qq/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals
import functools

from django.conf.urls import patterns, url
from django.contrib.admin.views.decorators import staff_member_required

from .views.record import CheckinListView
from .views.analysis import GroupByQQListView
from .views.import_data import UploadRecordList, upload

login_url = 'login'
staff_member_required = functools.partial(
    staff_member_required, login_url=login_url
)

urlpatterns = patterns(
    '',
    url(
        r'^records/checkins/$',
        staff_member_required(CheckinListView.as_view()),
        name='record_checkin_list'
    ),
)

urlpatterns += patterns(
    '',
    url(
        r'^analysis/group-by-qq/$',
        staff_member_required(GroupByQQListView.as_view()),
        name='analysis_group_by_qq_list'
    ),
)

urlpatterns += patterns(
    '',
    url(
        r'^imports/$',
        staff_member_required(UploadRecordList.as_view()),
        name='import_list'
    ),
    url(r'^imports/upload$', staff_member_required(upload), name='upload'),
)

chendian/member/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now
from django.utils.encoding import python_2_unicode_compatible

from core.db import LogicalDeleteMixin
from book.models import Book
from qq.models import CheckinRecord


@python_2_unicode_compatible
class Member(LogicalDeleteMixin):
    DEFAULT_AVATAR = settings.DEFAULT_MEMBER_AVATAR

    user = models.OneToOneField(User, related_name='member')

    sn = models.IntegerField('编号', db_index=True)
    qq = models.TextField('QQ', blank=True)
    nick_name = models.TextField('昵称', db_index=True, blank=True)
    avatar = models.URLField('头像', blank=True, default=DEFAULT_AVATAR)
    description = models.TextField('个人介绍', blank=True, default='个人介绍')
    books = models.ManyToManyField(Book, related_name='readers', blank=True)

    created_at = models.DateTimeField(default=now)
    updated_at = models.DateTimeField(default=now)
    last_read_at = models.DateTimeField(
        '最后一次读书时间', null=True, blank=True
    )

    class Meta:
        verbose_name = 'member'
        verbose_name_plural = 'members'

    def __str__(self):
        return '【{0}】{1}'.format(self.sn, self.nick_name)

    def save(self, *args, **kwargs):
        from qq.utils import update_member_info, update_member_books
        if not self.avatar:
            self.avatar = self.DEFAULT_AVATAR

        self.updated_at = now()
        if not (self.pk and self.user):
            user = User.objects.filter(username=self.qq)
            if not user.exists():
                user = User.objects.create_user(self.qq)
                user.set_password(settings.DEFAULT_PASSWORD)
                user.save()
            else:
                user = user[0]
            self.user = user

        new = True if not self.pk else False
        value = super(Member, self).save(*args, **kwargs)
        self.update_qq_record()
        if new:
            update_member_info.delay(self.pk)
            update_member_books.delay(self.pk)

        return value

    def update_qq_record(self):
        CheckinRecord.raw_objects.filter(qq=self.qq).update(
            sn=self.sn, nick_name=self.nick_name
        )


@python_2_unicode_compatible
class NewMember(LogicalDeleteMixin):
    status_need = 0
    status_approve = 1
    status_disappreove = 2
    status_choices = (
        (0, '待处理'),
        (1, '接受'),
        (2, '不接受'),
    )

    sn = models.IntegerField('编号')
    qq = models.TextField('QQ')
    nick_name = models.TextField('昵称')
    description = models.TextField('个人介绍', blank=True, default='个人介绍')
    status = models.SmallIntegerField(choices=status_choices,
                                      default=status_need)

    created_at = models.DateTimeField(default=now)
    updated_at = models.DateTimeField(default=now)
    last_read_at = models.DateTimeField(
        '最后一次读书时间', null=True, blank=True
    )

    class Meta:
        verbose_name = 'new_member'
        verbose_name_plural = 'new_members'

    def __str__(self):
        return 'New Member: 【{0}】{1}'.format(self.sn, self.nick_name)

    def approve(self):
        from qq.utils import update_member_info, update_member_books
        m = Member.raw_objects.filter(qq=self.qq).first()
        if m is None:
            m = Member()
        m.sn = self.sn
        m.qq = self.qq
        m.nick_name = self.nick_name
        m.description = self.description
        m.last_read_at = self.last_read_at
        m.save()
        update_member_info.delay(m.pk)
        update_member_books.delay(m.pk)

        self.status = self.status_approve
        self.save()
        return m

    def disapprove(self):
        self.status = self.status_disappreove
        self.save()

chendian/member/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django import forms
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    error_messages = {
        'invalid_login': '用户名或密码错误！',
        'no_cookies': '您的浏览器没有启用 Cookies！',
        'inactive': '此账户未激活！',
    }

chendian/api/member/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.http import Http404
from django.shortcuts import get_object_or_404

from rest_framework import status, filters
from rest_framework.generics import RetrieveUpdateDestroyAPIView
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response

from api._base import (
    OnlyFieldsModelViewMixin, ExcludeFieldsModelViewMixin,
    BaseListAPIView as ListAPIView, BaseAPIView as APIView
)
from api.book.serializers import BookSerializer
from api.qq.serializers import CheckinSerializer
from book.models import Book
from member.models import Member, NewMember
from qq.models import CheckinRecord
from .serializers import MemberSerializer, DynamicMemberSerializerClass


class MemberList(DynamicMemberSerializerClass,
                 ExcludeFieldsModelViewMixin,
                 OnlyFieldsModelViewMixin,
                 ListAPIView):
    model = Member
    queryset = Member.objects.all()
    serializer_class = MemberSerializer
    fields = [x.field_name for x in serializer_class()._readable_fields]
    filter_backends = (filters.DjangoFilterBackend,)
    filter_fields = ('sn', 'nick_name', 'qq')

    def post(self, request, format=None):
        serializer = MemberSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class MemberDetail(DynamicMemberSerializerClass,
                   RetrieveUpdateDestroyAPIView):
    model = Member
    queryset = Member.objects.all()
    serializer_class = MemberSerializer


class NewMemberApprove(APIView):
    permission_classes = (IsAdminUser,)

    def get_object(self, pk):
        try:
            return NewMember.objects.get(pk=pk)
        except NewMember.DoesNotExist:
            raise Http404

    def put(self, request, pk, format=None):
        member = self.get_object(pk)
        member.approve()
        return Response(status=status.HTTP_204_NO_CONTENT)

    def delete(self, request, pk, format=None):
        member = self.get_object(pk)
        member.disapprove()
        return Response(status=status.HTTP_204_NO_CONTENT)


class CheckinList(ListAPIView):
    model = CheckinRecord
    queryset = CheckinRecord.sorted_objects.all()
    serializer_class = CheckinSerializer

    def get_queryset(self):
        member = get_object_or_404(Member.objects.only('qq'),
                                   pk=self.kwargs['pk'])
        queryset = super(CheckinList, self).get_queryset()
        return queryset.filter(qq=member.qq).defer('raw_msg')


class BookList(ExcludeFieldsModelViewMixin,
               OnlyFieldsModelViewMixin,
               ListAPIView):
    model = Book
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    fields = [x.field_name for x in serializer_class()._readable_fields]

    def get_queryset(self):
        member = get_object_or_404(Member.objects.only('id'),
                                   pk=self.kwargs['pk'])
        queryset = super(BookList, self).get_queryset()
        return queryset.filter(readers=member)

chendian/frontend/views/member.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.core.urlresolvers import reverse_lazy
from django.http import Http404, HttpResponseRedirect
from django.views.generic.base import TemplateView


from member.models import Member


class MemberList(TemplateView):
    template_name = 'frontend/member/index.html'


class MemberDetail(TemplateView):
    template_name = 'frontend/member/detail.html'

    def get_context_data(self, **kwargs):
        context = super(MemberDetail, self).get_context_data(**kwargs)
        user = self.request.user
        pk = int(self.kwargs['pk'])

        context['editable'] = False
        if user.is_authenticated() and (
            user.is_staff or (user.member and user.member.pk == pk)
        ):
            context['editable'] = True
        context['id'] = pk
        return context


def member_sn(request, sn):
    member = Member.objects.filter(sn=sn).first()
    if member is None:
        raise Http404()
    return HttpResponseRedirect(
        reverse_lazy('frontend:member_detail', kwargs={'pk': member.pk})
    )

chendian/member/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""成员信息"""

from __future__ import absolute_import, print_function, unicode_literals

from django.contrib.auth import (
    login as dj_login, logout as dj_logout, authenticate
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic import ListView

from member.models import Member, NewMember
from .forms import LoginForm

LOGIN_URL = reverse_lazy('login')


class MemberListView(ListView):
    context_object_name = 'members'
    template_name = 'member/index.html'
    paginate_by = 50

    def get_queryset(self):
        sort = self.request.GET.get('sort', '-sn')
        kwargs = {}
        filter_by = self.request.GET.get('filter_by')
        value = self.request.GET.get('filter_value')
        if filter_by in ['id', 'sn', 'qq', 'nick_name'] and value:
            if filter_by == 'nick_name':
                kwargs['nick_name__contains'] = value
            elif filter_by in ['sn', 'id']:
                if value.isdigit():
                    kwargs[filter_by] = value
            else:
                kwargs[filter_by] = value

        queryset = Member.objects.filter(**kwargs)
        if sort and sort.lstrip('-') in [
            'sn', 'nick_name', 'qq'
        ]:
            queryset = queryset.order_by(sort)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(MemberListView, self).get_context_data(**kwargs)
        context.update({
            'has_new_member': NewMember.objects.filter(
                status=NewMember.status_need
            ).exists()
        })
        return context


class NewMemberListView(ListView):
    context_object_name = 'members'
    template_name = 'member/new_member.html'
    paginate_by = 50

    def get_queryset(self):
        sort = self.request.GET.get('sort', '-sn')
        kwargs = {'status': NewMember.status_need}
        filter_by = self.request.GET.get('filter_by')
        value = self.request.GET.get('filter_value')
        if filter_by in ['sn', 'qq', 'nick_name', 'status'] and value:
            if filter_by == 'nick_name':
                kwargs['nick_name__contains'] = value
            elif filter_by == 'sn':
                if value.isdigit():
                    kwargs[filter_by] = value
            else:
                kwargs[filter_by] = value

        queryset = NewMember.objects.filter(**kwargs)
        if sort and sort.lstrip('-') in [
            'sn', 'nick_name', 'qq', 'status'
        ]:
            queryset = queryset.order_by(sort)
        return queryset


def login(request, template_name='login.html',
          form_class=LoginForm, extra_context=None):
    """用户登录"""
    next_url = request.GET.get('next') or '/'
    form = form_class(data=request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            dj_login(request, user)
            return HttpResponseRedirect(next_url)

    context = {
        'form': form,
    }
    if extra_context:
        context.update(context)
    return render_to_response(template_name, context,
                              context_instance=RequestContext(request))


@login_required(login_url=LOGIN_URL)
def logout(request):
    next_url = request.GET.get('next') or '/'
    dj_logout(request)
    return HttpResponseRedirect(next_url)


@login_required(login_url=LOGIN_URL)
def change_password(request, template_name='change_password.html',
                    change_password_form=PasswordChangeForm,
                    extra_context=None):
    """修改密码"""
    form = change_password_form(request.user, request.POST or None)
    for field in form.fields.values():
        field.widget.attrs = {'class': 'form-control input-lg'}
    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/')
    context = {
        'form': form,
    }
    if extra_context:
        context.update(context)
    return render_to_response(template_name, context,
                              context_instance=RequestContext(request))

chendian/templates/member/index.html
{% extends "base.html" %}
{% load extra_tags %}

{% block title %}成员管理 - {{ block.super }} {% endblock title %}


{% block extra_head %}
<meta name="url-detail" content="{% url "api:member:member_detail" 0 %}">
{% endblock extra_head %}


{% block content %}

<div class="row">
  <h2>成员管理
    <small><a href="javascript: void(0);" class="label label-primary newMember">新增</a></small>
  </h2>

{% if has_new_member %}
  <div class="alert alert-warning alert-dismissible fade in" role="alert">
    {# <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button> #}
    <strong>发现未处理的新成员！</strong> <a href="{% url "member:new_member_list" %}">前去处理</a>
  </div>
{% endif %}

</div>


<div class="row">
  <form class="form-inline">
    <div class="form-group">
      <label class="sr-only" for="filter_by">选择</label>
        <select name="filter_by" class="form-control">
          <option value="sn"
          {% if request.GET.filter_by == "sn" %} selected {% endif %}
          >编号</option>
          <option value="qq"
          {% if request.GET.filter_by == "qq" %} selected {% endif %}
          >QQ</option>
          <option value="nick_name"
          {% if request.GET.filter_by == "nick_name" %} selected {% endif %}
          >昵称</option>
          <option value="id"
          {% if request.GET.filter_by == "id" %} selected {% endif %}
          >ID</option>
        </select>
    </div>
    <div class="form-group">
      <label class="sr-only" for="filter_name">值</label>
      <input class="form-control" type="text"
        name="filter_value" placeholder="value"
        value="{{ request.GET.filter_value }}" >
    </div>
    <input class="btn btn-primary" type="submit" value="过滤">
    <a class="btn btn-default" href="{{ request.path }}">重置</a>
  </form>
</div>

  {% include "page.html" %}


  <div class="row">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>
              {% sort_url_obj "sn" as sn_url %}
              <a href="{{ sn_url.new_url }}" class="{{ sn_url.sorting }}">编号
              {% if sn_url.sorting == "desc" %}
              <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
              {% elif sn_url.sorting == "asc" %}
              <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
              {% endif %}
              </a>
            </th>

            {% sort_url_obj "qq" as qq_url %}
            <th><a href="{{ qq_url.new_url }}" class="{{ qq_url.sorting }}">QQ
              {% if qq_url.sorting == "desc" %}
              <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
              {% elif qq_url.sorting == "asc" %}
              <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
              {% endif %}
              </a>
            </th>

            {% sort_url_obj "nick_name" as nick_name_url %}
            <th><a href="{{ nick_name_url.new_url }}" class="{{ nick_name_url.sorting }}">昵称
              {% if nick_name_url.sorting == "desc" %}
              <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
              {% elif nick_name_url.sorting == "asc" %}
              <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
              {% endif %}
              </a>
            </th>

            <th>个人简介</th>
            <th>查看</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          {% for member in page_obj.object_list %}
          <tr>
            <td>{{ member.sn }}</td>
            <td>{{ member.qq }}</td>
            <td>{{ member.nick_name }}</td>
            <td>{{ member.description|default:"" }}</td>
            <td>
              <a href="{% url 'qq:record_checkin_list' %}?filter_by=qq&filter_value={{ member.qq|urlencode }}">打卡记录</a>
              <a href="{% url 'qq:analysis_group_by_qq_list' %}?filter_by=qq&filter_value={{ member.qq|urlencode }}">打卡天数</a>
              <a href="{% url "frontend:member_detail" pk=member.pk %}">前台页面</a>
            </td>
            <td>
              <a class="edit_record" href="javascript: void(0);"
                data-reveal-id="edit_modal"
                data-id="{{ member.pk }}">编辑</a>
              <a class="delete_record" href="javascript: void(0);"
                data-id="{{ member.pk }}">删除</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
  </div>


  {% include "page.html" %}


  <div class="modal fade" id="add_modal" tabindex="-1" role="dialog"
    aria-hidden="true" >
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">新增成员</h4>
      </div>
      <div class="modal-body">

      <form action="#" id="add_form_post">
        {% csrf_token %}
          <div class="form-group">
            <label for="addSN">编号</label>
            <input class="form-control" type="number" name="sn" id="addSN" required>
          </div>
          <div class="form-group">
            <label for="addQQ">QQ</label>
            <input class="form-control" type="text" name="qq" id="addQQ" required>
          </div>
          <div class="form-group">
            <label for="addName">昵称</label>
            <input class="form-control" type="text" name="nick_name" id="addName" required>
          </div>
          <div class="form-group">
            <label for="addAvatar">头像</label>
            <input class="form-control" type="url" name="avatar" id="addAvatar" required>
          </div>
          <div class="form-group">
            <label for="addDescription">简介/备注</label>
            <textarea class="form-control" rows="3" name="description"
            id="addDescription"></textarea>
          </div>
    </form>

    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <a class="btn btn-primary" id="post_add_form" data-id="0"
        href="javascript: void(0);">保存</a>
    </div>
  </div>
  </div>
</div>
</div>




  <div class="modal fade" id="edit_modal" tabindex="-1" role="dialog"
    aria-hidden="true" >
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">编辑成员信息</h4>
      </div>
      <div class="modal-body">

    <div id="edit_form"></div>

    <script id="edit_form_template"  type="x-tmpl-mustache">
      <form action="#" id="edit_form_post">
        {% csrf_token %}

      {% verbatim %}
          <div class="form-group">
            <label for="editSN">编号</label>
            <input class="form-control" type="number" name="sn" id="editSN" value="{{sn}}">
          </div>
          <div class="form-group">
            <label for="editQQ">QQ</label>
            <input class="form-control" type="text" name="qq" id="editQQ" value="{{qq}}" readonly>
          </div>
          <div class="form-group">
            <label for="editName">昵称</label>
            <input class="form-control" type="text" name="nick_name" id="editName" value="{{nick_name}}">
          </div>
          <div class="form-group">
          <label for="editAvatar">头像 <a href="{{avatar}}" target="_blank">点击查看</a></label>
            <input class="form-control" type="url" name="avatar" id="editAvatar" value="{{avatar}}">
          </div>
          <div class="form-group">
            <label for="editDescription">简介/备注</label>
            <textarea class="form-control" rows="3" name="description"
            id="editDescription">{{description}}</textarea>
          </div>

        {% endverbatim %}

    </form>
  </script>

    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <a class="btn btn-primary" id="post_edit_form" data-id="0"
        href="javascript: void(0);">保存</a>
    </div>

  </div>
  </div>
</div>
</div>


  {% endblock content %}



  {% block extra_js %}
  <script src="{{ STATIC_URL }}js/frontend/normal/admin_member_index-10c4c82d88.js"></script>
  {% endblock extra_js %}

chendian/templates/member/new_member.html
{% extends "base.html" %}
{% load extra_tags %}

{% block title %}新成员管理 - {{ block.super }} {% endblock title %}


{% block extra_head %}
<meta name="url-detail" content="{% url "api:member:new_member_approve" 0 %}">
{% endblock extra_head %}


{% block content %}
<h2>处理新成员</h2>

  {% include "page.html" %}


  <div class="row">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>
              {% sort_url_obj "sn" as sn_url %}
              <a href="{{ sn_url.new_url }}" class="{{ sn_url.sorting }}">编号
              {% if sn_url.sorting == "desc" %}
              <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
              {% elif sn_url.sorting == "asc" %}
              <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
              {% endif %}
              </a>
            </th>

            {% sort_url_obj "qq" as qq_url %}
            <th><a href="{{ qq_url.new_url }}" class="{{ qq_url.sorting }}">QQ
              {% if qq_url.sorting == "desc" %}
              <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
              {% elif qq_url.sorting == "asc" %}
              <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
              {% endif %}
              </a>
            </th>

            {% sort_url_obj "nick_name" as nick_name_url %}
            <th><a href="{{ nick_name_url.new_url }}" class="{{ nick_name_url.sorting }}">昵称
              {% if nick_name_url.sorting == "desc" %}
              <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
              {% elif nick_name_url.sorting == "asc" %}
              <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
              {% endif %}
              </a>
            </th>

            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          {% for member in page_obj.object_list %}
          <tr>
            <td>{{ member.sn }}</td>
            <td>{{ member.qq }}</td>
            <td>{{ member.nick_name }}</td>
            <td>
              <a class="approve_record" href="javascript: void(0);"
                data-id="{{ member.pk }}">导入</a>
              <a class="delete_record" href="javascript: void(0);"
                data-id="{{ member.pk }}">忽略</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
  </div>


  {% include "page.html" %}

  {% endblock content %}


  {% block extra_js %}
  <script src="{{ STATIC_URL }}js/frontend/normal/admin_new_member_index-793ce3b023.js"></script>
  {% endblock extra_js %}