chendian/blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals
import functools

from django.conf.urls import patterns, url
from django.contrib.admin.views.decorators import staff_member_required

from .views import ArticleListView, TagListView, CategoryListView

login_url = 'login'
staff_member_required = functools.partial(
    staff_member_required, login_url=login_url
)

urlpatterns = patterns(
    '',
    url(
        r'^articles/$',
        staff_member_required(ArticleListView.as_view()),
        name='article_list'
    ),
    url(
        r'^tags/$',
        staff_member_required(TagListView.as_view()),
        name='tag_list'
    ),
    url(
        r'^categories/$',
        staff_member_required(CategoryListView.as_view()),
        name='category_list'
    ),
)

chendian/book/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals
import functools

from django.conf.urls import patterns, url
from django.contrib.admin.views.decorators import staff_member_required

from qq.views.index import HomeListView
from .views import BookListView

login_url = 'login'
staff_member_required = functools.partial(
    staff_member_required, login_url=login_url
)

urlpatterns = patterns(
    '',
    url(
        r'^$', staff_member_required(BookListView.as_view()), name='book_list'
    ),
    url(
        r'^hot/$', staff_member_required(HomeListView.as_view()),
        name='book_hot'
    ),
)

chendian/chendian/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import permission_required
# from django.views.generic import TemplateView

from qq.views.index import HomeListView

login_url = 'login'
admin_prefix = settings.ADMIN_PREFIX

urlpatterns = patterns(
    '',

    # Examples:
    # url(r'^$', 'chendian.views.home', name='home'),
    url(r'^admin123/$', permission_required(
        'member.member_add', login_url=login_url
    )(HomeListView.as_view()), name='admin123'
    ),
    url(r'^admin123/', include('qq.urls', namespace='qq')),
    url(r'^admin123/members/', include('member.urls', namespace='member')),
    url(r'^admin123/books/', include('book.urls', namespace='book')),
    url(r'^admin123/blog/', include('blog.urls', namespace='blog')),
    url(r'^api/', include('api.urls', namespace='api')),
    # url(r'^blog/', include('blog.urls')),

    url(r'^%s/' % admin_prefix, include(admin.site.urls)),

    url(r'', include('frontend.urls', namespace='frontend')),
)

urlpatterns += patterns(
    '',
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^login/$', 'member.views.login', name='login'),
    url(r'^logout/$', 'member.views.logout', name='logout'),
    url(r'^change-password/$', 'member.views.change_password',
        name='change_password'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

chendian/member/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals
import functools

from django.conf.urls import patterns, url
from django.contrib.admin.views.decorators import staff_member_required

from .views import MemberListView, NewMemberListView

login_url = 'login'
staff_member_required = functools.partial(
    staff_member_required, login_url=login_url
)

urlpatterns = patterns(
    '',
    url(
        r'^$', staff_member_required(MemberListView.as_view()),
        name='member_list'
    ),
    url(
        r'^new/$',
        staff_member_required(NewMemberListView.as_view()),
        name='new_member_list'
    ),
)

chendian/qq/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals
import functools

from django.conf.urls import patterns, url
from django.contrib.admin.views.decorators import staff_member_required

from .views.record import CheckinListView
from .views.analysis import GroupByQQListView
from .views.import_data import UploadRecordList, upload

login_url = 'login'
staff_member_required = functools.partial(
    staff_member_required, login_url=login_url
)

urlpatterns = patterns(
    '',
    url(
        r'^records/checkins/$',
        staff_member_required(CheckinListView.as_view()),
        name='record_checkin_list'
    ),
)

urlpatterns += patterns(
    '',
    url(
        r'^analysis/group-by-qq/$',
        staff_member_required(GroupByQQListView.as_view()),
        name='analysis_group_by_qq_list'
    ),
)

urlpatterns += patterns(
    '',
    url(
        r'^imports/$',
        staff_member_required(UploadRecordList.as_view()),
        name='import_list'
    ),
    url(r'^imports/upload$', staff_member_required(upload), name='upload'),
)

chendian/templates/base.html
<!doctype html>
<html lang="zh">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/ico" href="https://dn-tmp.qbox.me/chendian/cat_mouse_reading.jpg" />
    <title>{% block title %}沉淀书会后台管理{% endblock title %} </title>
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/bower_components/datetimepicker/jquery.datetimepicker.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/normalize.min.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/bower_components/font-awesome/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/bower_components/bootstrap-fileinput/css/fileinput.min.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/frontend/site-fa515a383b.css" />
    <style>
      body {
        padding-top: 70px;
      }
      span.select2-container {
        width: 100% !important;
      }
    </style>

    {% block extra_head %}{% endblock extra_head %}

  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url "admin123" %}">后台</a>
        </div>

      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav">

          <li><a href="{% url "member:member_list" %}">成员管理</a></li>
          <li><a href="{% url "qq:import_list" %}">数据导入</a></li>

          <li class="dropdown">
            <a href="javascript: void(0);"
              class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false"
              >打卡管理 <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url "qq:record_checkin_list" %}">打卡记录</a></li>
              <li><a href="{% url "qq:analysis_group_by_qq_list" %}">打卡天数</a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="javascript: void(0);"
              class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false"
              >书籍管理 <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url "book:book_list" %}">书籍列表</a></li>
              <li><a href="{% url "book:book_hot" %}">热门书籍</a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="javascript: void(0);"
              class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false"
              >文章管理 <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url "blog:article_list" %}">文章列表</a></li>
              <li><a href="{% url "blog:tag_list" %}">标签管理</a></li>
              <li><a href="{% url "blog:category_list" %}">分类管理</a></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="/">返回首页</a><li>
          <li><a href="javascript: void(0);">{{ request.user.username }}</a></li>
          <li><a href="{% url "logout" %}">退出</a></li>
        </ul>
      </div>
    </div>
  </nav>


      <div class="container">
          {% block content %}{% endblock content %}
      </div>

      <footer class="footer">
        <div class="container">
          {% block footer %}{% endblock %}
        </div>
      </footer>

    <script src="{{ STATIC_URL }}libs/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/bootstrap-fileinput/js/fileinput.min.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/datetimepicker/jquery.datetimepicker.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/mustache/mustache.min.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/xss/dist/xss.min.js"></script>
    <script src="{{ STATIC_URL }}js/frontend/normal/utils-44b7f01bd7.js"></script>
    <script src="{{ STATIC_URL }}js/frontend/normal/admin_base-fd4db35205.js"></script>

    {% block extra_js %}{% endblock extra_js %}

  </body>
</html>

chendian/templates/change_password.html
{% extends "frontend/base.html" %}

{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">修改密码</div>
  <div class="panel-body">
    {% if form.errors %}
    <div class="alert alert-danger">
      <p>请解决下面的错误</p>
    </div>
    {% endif %}

    <div>
      <form action="" method="post" class="form-horizontal">{% csrf_token %}
        {% for field in form %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
          <label for="{{ field.id_for_label }}" class="col-md-2 control-label">{{ field.label }}</label>
          <div class="col-md-10 ">
            {{ field }}
            {% if field.errors %}
            <span class='text-danger'>{{ field.errors|join:"<br />" }}</span>
            {% endif %}
            {% if field.help_text %}
            <span class="help-block ">{{ field.help_text }}</span>
            {% endif %}
          </div>
        </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <button type="reset" class="btn">重置</button>&nbsp;
            <button type="submit" class="btn btn-primary">更改密码</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

chendian/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="row">
  <h2>最近一个月({{ datetime_start|date:"m-d" }}
      ~ {{ datetime_end|date:"m-d" }})阅读人数 >2 的书籍</h2>
</div>


{% include "page.html" %}

<div class="row">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>书名</th>
        <th>阅读人数</th>
      </tr>
    </thead>
    <tbody>
      {% for item in page_obj.object_list %}
      <tr>
        {% with item.book_name|default:"" as book_name %}
        <td>
          <a href="{% url "book:book_list" %}?filter_by=name&filter_value={{ book_name }}">
            {{ book_name }}
          </a>
        </td>
        {% endwith %}
        <td><a href="{% url 'qq:record_checkin_list' %}?filter_by=book_name&filter_value={{ item.book_name|urlencode }}">{{ item.count }}</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% include "page.html" %}

{% endblock content %}

chendian/templates/login.html
{% extends "base.html" %}

{% block title %}登录 - 沉淀书会 {% endblock title %}

{% block extra_head %}
<style>
  nav {
    display: none;
  }
</style>
{% endblock extra_head %}

{% block content %}
<form class="form-login" method="post">
  <fieldset>
    <legend><h2>登录书会帐号</h2></legend>
  </fieldset>
  {% csrf_token %}

  {% if form.errors %}
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>用户名或密码错误！</strong>
  </div>
  {% endif %}

  <div class="{% if form.errors %}has-error{% endif %}">
    <lable for="inputUsername" class="sr-only">用户名</lable>
    <input type="text" id="inputUsername" name="username" required
    class="form-control" placeholder="用户名" value="{{ form.username.value|default:"" }}">
    <lable for="inputPassword" class="sr-only">密码</lable>
    <input type="password" id="inputPassword" name="password" required
    class="form-control" placeholder="密码">
  </div>
  <input type="submit" class="btn btn-lg btn-primary btn-block" value="登录">
</form>
{% endblock content %}

chendian/templates/page.html
{% load extra_tags %}

{% if is_paginated %}
<div class="row">

<ul class="pager">
  {% if page_obj.has_previous %}
  <li class="previous">
    <a href="{% page_url page_obj.previous_page_number %}">
      <span aria-hidden="true">&larr;</span>上一页</a>
  </li>
  {% else %}
  <li class="previous disabled">
    <a href="#"><span aria-hidden="true">&larr;</span>上一页</a>
  </li>
  {% endif %}

  <li>{{ page_obj.number }}/{{ page_obj.paginator.num_pages }}</li>

  {% if page_obj.has_next %}
  <li class="next">
    <a href="{% page_url page_obj.next_page_number %}">下一页<span aria-hidden="true">&rarr;</span></a>
  </li>
  {% else %}
  <li class="next disabled">
    <a href="#">下一页<span aria-hidden="true">&rarr;</span></a>
  </li>
  {% endif %}

</ul>

</div>
{% endif %}