chendian/chendian/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import permission_required
# from django.views.generic import TemplateView

from qq.views.index import HomeListView

login_url = 'login'
admin_prefix = settings.ADMIN_PREFIX

urlpatterns = patterns(
    '',

    # Examples:
    # url(r'^$', 'chendian.views.home', name='home'),
    url(r'^admin123/$', permission_required(
        'member.member_add', login_url=login_url
    )(HomeListView.as_view()), name='admin123'
    ),
    url(r'^admin123/', include('qq.urls', namespace='qq')),
    url(r'^admin123/members/', include('member.urls', namespace='member')),
    url(r'^admin123/books/', include('book.urls', namespace='book')),
    url(r'^admin123/blog/', include('blog.urls', namespace='blog')),
    url(r'^api/', include('api.urls', namespace='api')),
    # url(r'^blog/', include('blog.urls')),

    url(r'^%s/' % admin_prefix, include(admin.site.urls)),

    url(r'', include('frontend.urls', namespace='frontend')),
)

urlpatterns += patterns(
    '',
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^login/$', 'member.views.login', name='login'),
    url(r'^logout/$', 'member.views.logout', name='logout'),
    url(r'^change-password/$', 'member.views.change_password',
        name='change_password'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

chendian/frontend/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from .views.blog import ArticleList, ArticleDetail
from .views.book import BookDetail, BookList, book_name
from .views.member import MemberList, MemberDetail, member_sn


urlpatterns = patterns(
    '',
    url(
        r'^$', RedirectView.as_view(url='/a/', permanent=False),
        name='blog_home'
    ),

    # 文章
    url(r'^a/$', ArticleList.as_view(), name='article_list'),
    url(r'^a/(?P<pk>\d+)/$', ArticleDetail.as_view(), name='article_detail'),

    # 书籍
    url(r'^b/$', BookList.as_view(), name='book_list'),
    url(r'^b/(?P<pk>\d+)/$', BookDetail.as_view(), name='book_detail'),
    url(r'^b/name/(?P<name>[^/]{2,50})/$', book_name, name='book_name'),

    # 成员
    url(r'^m/$', MemberList.as_view(), name='member_list'),
    url(r'^m/(?P<pk>\d+)/$', MemberDetail.as_view(), name='member_detail'),
    url(r'^m/sn/(?P<sn>\d+)/$', member_sn, name='member_sn'),

    # 吐槽
    url(
        r'^feedback/$', TemplateView.as_view(
            template_name='frontend/feedback.html'
        ),
        name='feedback'
    ),
)

chendian/qq/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals
import functools

from django.conf.urls import patterns, url
from django.contrib.admin.views.decorators import staff_member_required

from .views.record import CheckinListView
from .views.analysis import GroupByQQListView
from .views.import_data import UploadRecordList, upload

login_url = 'login'
staff_member_required = functools.partial(
    staff_member_required, login_url=login_url
)

urlpatterns = patterns(
    '',
    url(
        r'^records/checkins/$',
        staff_member_required(CheckinListView.as_view()),
        name='record_checkin_list'
    ),
)

urlpatterns += patterns(
    '',
    url(
        r'^analysis/group-by-qq/$',
        staff_member_required(GroupByQQListView.as_view()),
        name='analysis_group_by_qq_list'
    ),
)

urlpatterns += patterns(
    '',
    url(
        r'^imports/$',
        staff_member_required(UploadRecordList.as_view()),
        name='import_list'
    ),
    url(r'^imports/upload$', staff_member_required(upload), name='upload'),
)

chendian/frontend/views/blog.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.views.generic.base import TemplateView


class ArticleList(TemplateView):
    template_name = 'frontend/blog/article_list.html'


class ArticleDetail(TemplateView):
    template_name = 'frontend/blog/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ArticleDetail, self).get_context_data(**kwargs)
        context['id'] = self.kwargs['pk']
        return context

chendian/frontend/views/book.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.core.urlresolvers import reverse_lazy
from django.http import Http404, HttpResponseRedirect
from django.views.generic.base import TemplateView

from book.models import Book


class BookList(TemplateView):
    template_name = 'frontend/book/index.html'


class BookDetail(TemplateView):
    template_name = 'frontend/book/detail.html'

    def get_context_data(self, **kwargs):
        context = super(BookDetail, self).get_context_data(**kwargs)
        context['id'] = self.kwargs['pk']
        return context


def book_name(request, name):
    book = Book.objects.filter(name=name).first()
    if book is None:
        raise Http404()
    return HttpResponseRedirect(
        reverse_lazy('frontend:book_detail', kwargs={'pk': book.pk})
    )

chendian/frontend/views/member.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.core.urlresolvers import reverse_lazy
from django.http import Http404, HttpResponseRedirect
from django.views.generic.base import TemplateView


from member.models import Member


class MemberList(TemplateView):
    template_name = 'frontend/member/index.html'


class MemberDetail(TemplateView):
    template_name = 'frontend/member/detail.html'

    def get_context_data(self, **kwargs):
        context = super(MemberDetail, self).get_context_data(**kwargs)
        user = self.request.user
        pk = int(self.kwargs['pk'])

        context['editable'] = False
        if user.is_authenticated() and (
            user.is_staff or (user.member and user.member.pk == pk)
        ):
            context['editable'] = True
        context['id'] = pk
        return context


def member_sn(request, sn):
    member = Member.objects.filter(sn=sn).first()
    if member is None:
        raise Http404()
    return HttpResponseRedirect(
        reverse_lazy('frontend:member_detail', kwargs={'pk': member.pk})
    )

chendian/templates/frontend/base.html
<!doctype html>
<html lang="zh">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/ico" href="https://dn-tmp.qbox.me/chendian/cat_mouse_reading.jpg" />
    <title>{% block title %}沉淀书会{% endblock title %} </title>
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/normalize.min.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/bower_components/select2/dist/css/select2.min.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/bower_components/summernote/dist/summernote.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/bower_components/font-awesome/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/bower_components/dropzone/dist/min/basic.min.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/bower_components/dropzone/dist/min/dropzone.min.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}libs/jquery-ajax-progress-bar/jquery-ajax-progress-bar.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/frontend/site-fa515a383b.css" />

    <style>
      body {
        padding-top: 70px;
      }
      span.select2-container {
        width: 100% !important;
      }
    </style>

    {% block extra_head %}{% endblock extra_head %}

  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">沉淀书会</a>
        </div>

      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{% url "frontend:article_list" %}">文章</a></li>
          <li><a href="{% url "frontend:book_list" %}">书籍</a></li>
          <li><a href="{% url "frontend:member_list" %}">成员</a></li>
          <li><a href="{% url "frontend:feedback" %}">吐槽</a></li>

          {% if request.user.is_authenticated %}
          <li>
            <a href="javascript: void(0);" data-toggle="modal" data-target=".bs-new-post-modal-lg">
              <i class="fa fa-paw fa-lg"></i> 投稿
            </a>
          </li>
          {% endif %}

        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
            {% include "frontend/topbar_userinfo.html" %}
          {% else %}
            <li><a href="{% url "login" %}">登录</a></li>
          {% endif %}
        </ul>

      </div>
    </div>
  </nav>

      <div class="container">
        <div class="row">
          <div class="col-md-12">
            {% block content %}{% endblock content %}
          </div>
        </div>
      </div>

    <footer class="footer">
      {% include "frontend/new_post_form.html" %}
      <div class="container">
        {% block footer %}{% endblock %}
      </div>
    </footer>

    <script src="{{ STATIC_URL }}libs/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    {% if debug %}
    <script src="{{ STATIC_URL }}libs/bower_components/react/react.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/react/react-dom.js"></script>
    {% else %}
    <script src="{{ STATIC_URL }}libs/bower_components/react/react.min.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/react/react-dom.min.js"></script>
    {% endif %}

    <script src="{{ STATIC_URL }}libs/bower_components/select2/dist/js/select2.full.min.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/summernote/dist/summernote.min.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/summernote/lang/summernote-zh-CN.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/xss/dist/xss.min.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/dropzone/dist/min/dropzone.min.js"></script>
    <script src="{{ STATIC_URL }}libs/bower_components/isMobile/isMobile.min.js"></script>
    <script src="{{ STATIC_URL }}libs/jquery-ajax-progress-bar/jquery-ajax-progress-bar.js"></script>

    <script src="{{ STATIC_URL }}js/site.js?1234"></script>
    <script src="{{ STATIC_URL }}js/frontend/normal/utils-44b7f01bd7.js"></script>
    <script src="{{ STATIC_URL }}js/frontend/mixins-85b17a1585.js"></script>
    <script src="{{ STATIC_URL }}js/frontend/normal/new_post-1c32c3d5bd.js"></script>

    <script>
    $(function() {
      $.ajaxSetup({
        dataType: 'json',
        contentType: 'application/json'
      });

      heightlightNav();
    });
    </script>

    {% block extra_js %}{% endblock extra_js %}

  </body>
</html>

chendian/templates/frontend/feedback.html
{% extends "frontend/base.html" %}


{% block title %}吐个槽儿~~~{{ block.super }}{% endblock title %}


{% block content %}
<p>
  <img src="https://dn-tmp.qbox.me/chendian/cattt.jpg" style="max-width: 100%"/>
  欢迎到此吐个槽儿~~~
</p>
{% endblock content %}


{% block extra_js %}
<!-- 多说评论框 start -->
  <div class="ds-thread container" data-thread-key="feedback" data-title="吐槽~" data-url="http://cd.3sd.me/feedback/"></div>
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"chendian"};
  (function() {
    var ds = document.createElement('script');
    ds.type = 'text/javascript';ds.async = true;
    ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
    ds.charset = 'UTF-8';
    (document.getElementsByTagName('head')[0] 
     || document.getElementsByTagName('body')[0]).appendChild(ds);
  })();
  </script>
<!-- 多说公共JS代码 end -->
{% endblock extra_js %}

chendian/templates/frontend/new_post_form.html
<div class="modal fade bs-new-post-modal-lg" tabindex="-1" role="dialog" aria-labelledby="newPostModalLabel" id="newPostModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="newPostModalLabel">投稿</h4>
      </div>
      <div class="modal-body">
        <form id="newPostForm">
          <div class="form-group">
            <label for="title">标题</label>
            <input type="text" class="form-control" id="title"
            placeholder="标题" required name="title">
          </div>
          <div class="form-group">
            <label for="categories">分类</label>
            <select class="form-control" id="categories"
              name="category_list" required multiple>
              <option value=""></option>
            </select>
          </div>
          <div class="form-group">
            <label for="tags">标签（可以通过“标签名称+,”的方式新增标签）</label>
            <select class="form-control" id="tags" name="tag_list" multiple>
              <option value=""></option>
            </select>
          </div>
          <div class="form-group">
            <label for="new-post-content">内容</label>
            <textarea class="form-control" id="new-post-content" name="content"
              rows="3" required></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary" id="newPostButton">投递</button>
      </div>
    </div> <!-- /.modal-content -->
  </div> <!-- /.modal-dialog -->
</div> <!-- /.modal -->

chendian/templates/frontend/topbar_userinfo.html
  {% if request.user.is_staff %}
  <li><a href="{% url "admin123" %}">进入后台管理系统</a><li>
  {% endif %}

  <li>
  <a href="javascript: void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    {{ request.user.member.nick_name }}<span class="caret"></span>
  </a>
    <ul class="dropdown-menu" role="menu">
      {% if request.user.member %}
      <li><a href="{% url "frontend:member_detail" pk=request.user.member.id %}">修改个人信息</a></li>
      {% else %}
      <li><a href="javascript: void(0);">修改个人信息</a></li>
      {% endif %}
      <li><a href="{% url "change_password" %}">修改密码</a></li>
    </ul>
  </li>
  <li><a href="{% url "logout" %}">退出</a></li>