chendian/api/qq/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf.urls import patterns, url

from .record import CheckinList, CheckinDetail

urlpatterns = patterns(
    '',
    url(r'^checkins/$', CheckinList.as_view(),
        name='checkin_list'),
    url(r'^checkins/(?P<pk>\d+)/$', CheckinDetail.as_view(),
        name='checkin_detail'),
)

chendian/chendian/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import permission_required
# from django.views.generic import TemplateView

from qq.views.index import HomeListView

login_url = 'login'
admin_prefix = settings.ADMIN_PREFIX

urlpatterns = patterns(
    '',

    # Examples:
    # url(r'^$', 'chendian.views.home', name='home'),
    url(r'^admin123/$', permission_required(
        'member.member_add', login_url=login_url
    )(HomeListView.as_view()), name='admin123'
    ),
    url(r'^admin123/', include('qq.urls', namespace='qq')),
    url(r'^admin123/members/', include('member.urls', namespace='member')),
    url(r'^admin123/books/', include('book.urls', namespace='book')),
    url(r'^admin123/blog/', include('blog.urls', namespace='blog')),
    url(r'^api/', include('api.urls', namespace='api')),
    # url(r'^blog/', include('blog.urls')),

    url(r'^%s/' % admin_prefix, include(admin.site.urls)),

    url(r'', include('frontend.urls', namespace='frontend')),
)

urlpatterns += patterns(
    '',
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^login/$', 'member.views.login', name='login'),
    url(r'^logout/$', 'member.views.logout', name='logout'),
    url(r'^change-password/$', 'member.views.change_password',
        name='change_password'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

chendian/qq/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals
import functools

from django.conf.urls import patterns, url
from django.contrib.admin.views.decorators import staff_member_required

from .views.record import CheckinListView
from .views.analysis import GroupByQQListView
from .views.import_data import UploadRecordList, upload

login_url = 'login'
staff_member_required = functools.partial(
    staff_member_required, login_url=login_url
)

urlpatterns = patterns(
    '',
    url(
        r'^records/checkins/$',
        staff_member_required(CheckinListView.as_view()),
        name='record_checkin_list'
    ),
)

urlpatterns += patterns(
    '',
    url(
        r'^analysis/group-by-qq/$',
        staff_member_required(GroupByQQListView.as_view()),
        name='analysis_group_by_qq_list'
    ),
)

urlpatterns += patterns(
    '',
    url(
        r'^imports/$',
        staff_member_required(UploadRecordList.as_view()),
        name='import_list'
    ),
    url(r'^imports/upload$', staff_member_required(upload), name='upload'),
)

chendian/qq/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.db import models
from django.utils.timezone import now
from django.utils.encoding import python_2_unicode_compatible

from core.db import LogicalDeleteMixin, ValidObjectManager
from core.utils import utc_to_local


class ReversePostedAtManager(ValidObjectManager):
    def get_queryset(self):
        return super(ReversePostedAtManager, self
                     ).get_queryset().order_by('-posted_at')


@python_2_unicode_compatible
class RawMessage(LogicalDeleteMixin):
    nick_name = models.TextField('昵称')
    qq = models.TextField('QQ')
    sn = models.IntegerField('编号', blank=True, null=True)
    msg = models.TextField('消息内容', default='')
    raw_item = models.TextField('整个记录内容', default='')
    posted_at = models.DateTimeField('发言时间', db_index=True)

    objects = models.Manager()
    sorted_objects = ReversePostedAtManager()

    class Meta:
        verbose_name = '聊天记录'
        verbose_name_plural = '聊天记录'

    @property
    def posted_at_local(self):
        return utc_to_local(self.posted_at)

    def __str__(self):
        return '{0} at {1}'.format(self.nick_name, self.posted_at)


@python_2_unicode_compatible
class CheckinRecord(LogicalDeleteMixin):
    raw_msg = models.OneToOneField(RawMessage, verbose_name='原始聊天记录')

    nick_name = models.TextField('昵称')
    sn = models.IntegerField('编号', blank=True, null=True, db_index=True)
    qq = models.TextField('QQ', db_index=True)
    book_name = models.TextField('书名', blank=True, default='', db_index=True)
    think = models.TextField('读后感', default='', blank=True)
    posted_at = models.DateTimeField('打卡时间', db_index=True)

    sorted_objects = ReversePostedAtManager()

    class Meta:
        verbose_name = '打卡记录'
        verbose_name_plural = '打卡记录'

    @property
    def posted_at_local(self):
        return utc_to_local(self.posted_at)

    def __str__(self):
        return '{0} at {1}'.format(self.nick_name, self.posted_at)


@python_2_unicode_compatible
class UploadRecord(LogicalDeleteMixin):
    status_progress = 1
    status_finish = 2
    status_error = 3
    status_choices = (
        (status_progress, '处理中'),
        (status_finish, '完成'),
        (status_error, '错误'),
    )
    status = models.SmallIntegerField(choices=status_choices,
                                      default=status_progress)
    type_qq = 1
    type_lofter = 2
    type_hundred_goal_note = 3
    type_choices = (
        (type_qq, 'QQ 群聊天记录(txt)'),
        (type_lofter, 'Lofter 博客导出的文件(xml)'),
        (type_hundred_goal_note, '百日斩打卡记录(html)'),
    )
    type = models.SmallIntegerField(choices=type_choices,
                                    default=type_qq)
    count = models.IntegerField(default=0)
    error = models.TextField(default='')
    text = models.TextField(default='')

    created_at = models.DateTimeField(default=now)
    update_at = models.DateTimeField(default=now)

    class Meta:
        verbose_name = '上传记录'
        verbose_name_plural = '上传记录'

    def __str__(self):
        return '{0} at {1}'.format(self.update_at, self.status)

    def parse_text(self):
        """分析记录"""
        from blog.utils import import_lofter
        from qq.utils import save_uploaded_text, import_hundred_goal_note
        if self.type == self.type_qq:
            save_uploaded_text.delay(self.pk)
        elif self.type == self.type_hundred_goal_note:
            import_hundred_goal_note.delay(self.pk)
        elif self.type == self.type_lofter:
            import_lofter.delay(self.pk)

chendian/qq/views/analysis.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""统计分析"""

from __future__ import absolute_import, print_function, unicode_literals

from collections import OrderedDict
import logging

from django.views.generic import ListView

from core.aggregates import CountWithFunc
from core.utils import xlsx_response
from qq.models import CheckinRecord
from qq.utils import record_filter_kwargs

logger = logging.getLogger(__name__)


class GroupByQQListView(ListView):
    context_object_name = 'records'
    template_name = 'qq/analysis/group_by_qq.html'
    paginate_by = 50

    def get_queryset(self):
        sort = self.request.GET.get('sort', '-count')
        kwargs = record_filter_kwargs(self.request)
        self.extra_context = {
            'datetime_start': kwargs['posted_at__gte'],
            'datetime_end': kwargs['posted_at__lte'],
            'book_name': kwargs.get('book_name', ''),
        }
        kwargs.update({'deleted': False})

        queryset = CheckinRecord.objects.filter(**kwargs)
        queryset = queryset.values(
            'sn', 'qq', 'nick_name'
        ).annotate(
            count=CountWithFunc(
                "date_trunc('day', posted_at::TIMESTAMPTZ AT TIME ZONE "
                "'+08:00'::INTERVAL)",
                distinct=True
            )
        )
        logger.debug(queryset.query)
        if sort and sort.lstrip('-') in ['sn', 'nick_name', 'qq', 'count']:
            queryset = queryset.order_by(sort)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(GroupByQQListView, self).get_context_data(**kwargs)
        context.update(self.extra_context)
        return context

    def render_to_response(self, context, **response_kwargs):
        if self.request.GET.get('export') != 'xlsx':
            return super(GroupByQQListView, self).render_to_response(
                context, **response_kwargs
            )

        queryset = self.get_queryset()
        xlsx_headers = OrderedDict([
            ('编号', 'sn'),
            ('昵称', 'nick_name'),
            ('QQ', 'qq'),
            ('打卡天数', 'count'),
        ])
        filename = u'%s-%s打卡情况' % (
            self.extra_context['datetime_start'],
            self.extra_context['datetime_end']
        )
        return xlsx_response(xlsx_headers, queryset, filename)

chendian/qq/views/import_data.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

import collections
from time import time

from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import ListView

from qq.models import UploadRecord


def upload(request, extra_context=None):
    if request.method == 'POST':
        text = request.FILES.get('text').read().decode('utf-8-sig')
        type = request.POST.get('type', UploadRecord.type_qq)
        if type not in map(str, dict(UploadRecord.type_choices)):
            type = UploadRecord.type_qq
        else:
            type = int(type)
        r = UploadRecord.objects.create(text=text, type=int(type))
        r.parse_text()

    return HttpResponseRedirect(reverse_lazy('qq:import_list')
                                + '?%s' % time())


class UploadRecordList(ListView):
    context_object_name = 'records'
    template_name = 'qq/import.html'
    paginate_by = 30

    def get_queryset(self):
        queryset = UploadRecord.objects.all()
        queryset = queryset.defer('text').order_by('-update_at')
        return queryset

    def get_context_data(self, **kwargs):
        context = super(UploadRecordList, self).get_context_data(**kwargs)
        context['types'] = collections.OrderedDict(
            reversed(UploadRecord.type_choices)
        )
        return context

chendian/qq/views/index.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.db.models import Count
# from django.shortcuts import render_to_response
# from django.template import RequestContext
from django.views.generic import ListView

from qq.models import CheckinRecord
from qq.utils import record_filter_kwargs
#
#
# def home(request, template_name='index.html'):
#     kwargs = record_filter_kwargs(request)
#     kwargs.update({'deleted': False})
#     books = CheckinRecord.objects.filter(**kwargs).exclude(
#         book_name=''
#     ).values('book_name').annotate(
#         count=Count('pk')
#     )
#
#     context = {
#         'books': books,
#         'datetime_start': kwargs['posted_at__gte'],
#         'datetime_end': kwargs['posted_at__lte'],
#     }
#     return render_to_response(
#         template_name, context, context_instance=RequestContext(request)
#     )


class HomeListView(ListView):
    context_object_name = 'books'
    template_name = 'index.html'
    paginate_by = 50

    def get_queryset(self):
        sort = self.request.GET.get('sort', '-count')
        kwargs = record_filter_kwargs(self.request)
        self.extra_context = {
            'datetime_start': kwargs['posted_at__gte'],
            'datetime_end': kwargs['posted_at__lte'],
        }
        kwargs.update({'deleted': False})

        queryset = CheckinRecord.objects.filter(**kwargs).exclude(
            book_name=''
        ).values('book_name').annotate(
            count=Count('qq', distinct=True)
        ).filter(count__gt=2)

        if sort and sort.lstrip('-') in ['book_name', 'count']:
            queryset = queryset.order_by(sort)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HomeListView, self).get_context_data(**kwargs)
        context.update(self.extra_context)
        return context

chendian/qq/views/record.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""打卡记录"""

from __future__ import absolute_import, print_function, unicode_literals

from django.views.generic import ListView

from qq.models import CheckinRecord
from qq.utils import record_filter_kwargs


class CheckinListView(ListView):
    context_object_name = 'records'
    template_name = 'qq/record/checkin.html'
    paginate_by = 50

    def get_queryset(self):
        sort = self.request.GET.get('sort')
        kwargs = record_filter_kwargs(self.request)
        self.extra_context = {
            'datetime_start': kwargs['posted_at__gte'],
            'datetime_end': kwargs['posted_at__lte'],
        }

        queryset = CheckinRecord.sorted_objects.filter(**kwargs)
        if sort and sort.lstrip('-') in [
            'sn', 'nick_name', 'qq', 'book_name', 'posted_at'
        ]:
            queryset = queryset.order_by(sort)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CheckinListView, self).get_context_data(**kwargs)
        context.update(self.extra_context)
        return context

chendian/templates/qq/filter_form.html
<div class="row">
  <form class="form-inline">
    <div class="form-group">
      <label class="sr-only" for="filter_by">选择</label>
        <select name="filter_by" class="form-control">
          <option value="sn"
          {% if request.GET.filter_by == "sn" %} selected {% endif %}
          >编号</option>
          <option value="qq"
          {% if request.GET.filter_by == "qq" %} selected {% endif %}
          >QQ</option>
          <option value="nick_name"
          {% if request.GET.filter_by == "nick_name" %} selected {% endif %}
          >昵称</option>
          <option value="book_name"
          {% if request.GET.filter_by == "book_name" %} selected {% endif %}
          >书名</option>
          <option value="id"
          {% if request.GET.filter_by == "id" %} selected {% endif %}
          >ID</option>
        </select>
    </div>
    <div class="form-group">
      <label class="sr-only" for="filter_name">值</label>
      <input class="form-control" type="text"
        name="filter_value" placeholder="value"
        value="{{ request.GET.filter_value }}" >
    </div>
    <div class="form-group">
      <label for="datetime_start">开始时间</label>
      <input class="form-control" type="text"
      name="datetime_start" id="datetime_start"
      value="{{ datetime_start|date:"Y-m-d H:i" }}"
      >
    </div>
    <div class="form-group">
          <label for="datetime_end">结束时间</label>
          <input class="form-control" type="text" name="datetime_end"
            id="datetime_end" value="{{ datetime_end|date:"Y-m-d H:i" }}" >
        </div>
    <input class="btn btn-primary" type="submit" value="过滤">
    <a class="btn btn-default" href="{{ request.path }}">重置</a>
    {% url "qq:analysis_group_by_qq_list" as a_url %}
    {% if request.path == a_url %}
    <a class="btn btn-info" href="?{{ request.GET.urlencode|default:"foo" }}&export=xlsx">导出</a>
    {% endif %}
  </form>
</div>

chendian/templates/qq/import.html
{% extends "base.html" %}

{% block title %}数据导入 - {{ block.super }} {% endblock title %}

{% block content %}
<h2>数据导入</h2>

<div class="row">
  <form class="form-inline" method="post"
    action="{% url "qq:upload" %}" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="form-group">
        <select class="form-control" name="type" required>
          {% for key, value in types.items %}
          <option value="{{ key }}">{{ value }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <input class="form-control" type="file" name="text" placeholder="value" required>
      </div>
        <input type="submit" class="btn btn-primary" value="上传">
  </form>
</div>




  {% include "page.html" %}


  <div class="row">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>类别</th>
            <th>状态</th>
            <th>解析记录数</th>
            <th>添加日期</th>
            <th>更新日期</th>
          </tr>
        </thead>
        <tbody>
          {% for record in page_obj.object_list %}
          <tr>
            <td>{{ record.pk }}</td>
            <td>{{ record.get_type_display }}</td>
            <td>{{ record.get_status_display }}</td>
            <td>{{ record.count }}</td>
            <td>{{ record.created_at|date:"Y-m-d H:i:s" }}</td>
            <td>{{ record.update_at|date:"Y-m-d H:i:s" }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
  </div>


  {% include "page.html" %}

  {% endblock content %}